# Generated by Django 5.1 on 2024-11-18 19:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Заголовок страницы"),
                ),
                (
                    "show_in_list",
                    models.BooleanField(
                        default=True, verbose_name="Показывать в общем списке на сайте"
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False, verbose_name="Отключить страницу"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="pages/images/%Y/%m/%d/",
                        verbose_name="Изображение страницы",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", verbose_name="Содержимое страницы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
            },
        ),
    ]
