services:
  backend:
    build:
      context: ./backend
    container_name: pandoraWebsiteBackend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
      - static_volume:/app/static
      - ./backend/.env:/app/.env
      - ./backend/db:/app/db

  frontend:
    build:
      context: ./frontend
    container_name: pandoraWebsiteFrontend
    environment:
      - DOMAIN_ADDRESS="domain"
    ports:
      - "80:80"
    volumes:
      - static_volume:/static/
      - ./backend/media:/media/
      - /etc/letsencrypt/live/${DOMAIN_ADDRESS}:/keys
    depends_on:
      - backend

volumes:
  static_volume: