services:
  backend:
    build:
      context: ./backend
    container_name: pandoraWebsiteBackend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
      - static_volume:/app/static
      - ./backend/.env:/app/.env
      - ./backend/db:/app/db

  frontend:
    build:
      context: ./frontend
    container_name: pandoraWebsiteFrontend
    ports:
      - "80:80"
    volumes:
      - static_volume:/static/
      - ./backend/media:/media/
      - /etc/letsencrypt/live/domain:/keys
    depends_on:
      - backend

volumes:
  static_volume: