# Generated by Django 5.1 on 2024-11-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directions", "0001_initial"),
        ("halls", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст объявления")),
                (
                    "start_display",
                    models.DateTimeField(verbose_name="Начало отображения объявления"),
                ),
                (
                    "end_display",
                    models.DateTimeField(
                        verbose_name="Окончание отображения объявления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["start_display"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала занятия")),
                ("end_time", models.TimeField(verbose_name="Время окончания занятия")),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="directions.direction",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="halls.hall",
                        verbose_name="Зал",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        related_name="schedules",
                        to="teachers.teacher",
                        verbose_name="Преподаватели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент рассписания",
                "verbose_name_plural": "Элементы рассписания",
                "ordering": ["weekday", "start_time"],
            },
        ),
    ]
