# Generated by Django 5.1 on 2024-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="remark",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Примечание"
            ),
        ),
    ]
