# Generated by Django 5.1 on 2024-11-18 19:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Имя преподавателя"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        upload_to="teachers/avatars/", verbose_name="Аватарка учителя"
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", verbose_name="О тренере"
                    ),
                ),
                (
                    "directions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="directions.direction",
                        verbose_name="Направления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренеры",
            },
        ),
    ]
