# Generated by Django 5.1 on 2024-11-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название соц. сети"),
                ),
                ("link", models.URLField(verbose_name="Ссылка на соц. сеть")),
                (
                    "icon",
                    models.CharField(
                        max_length=100, verbose_name="Имя в файле с иконками"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
