# Generated by Django 5.1 on 2024-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="social",
            old_name="link",
            new_name="direct_link",
        ),
        migrations.AddField(
            model_name="social",
            name="internal_link",
            field=models.CharField(default="", max_length=100, verbose_name="Ссылка"),
            preserve_default=False,
        ),
    ]
