# Generated by Django 5.1 on 2025-01-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_rename_link_social_direct_link_social_internal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='direct_link',
            field=models.URLField(verbose_name='Ссылка прямая (https://...)'),
        ),
        migrations.AlterField(
            model_name='social',
            name='internal_link',
            field=models.CharField(max_length=100, verbose_name='Ссылка внутренняя (@nametag)'),
        ),
    ]
