# Generated by Django 5.1 on 2024-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Callback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="Номер телефона"),
                ),
                (
                    "telegram_allowed",
                    models.BooleanField(default=False, verbose_name="Разрешен ли tg"),
                ),
                (
                    "whatsapp_allowed",
                    models.BooleanField(default=False, verbose_name="Разрешен ли wa"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания заявки"
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки заявки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратный звонок",
                "verbose_name_plural": "Обратные звонки",
                "ordering": ["-created_at"],
            },
        ),
    ]
