# Generated by Django 5.1 on 2025-01-06 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='name',
            field=models.CharField(default='Ivan', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заявки'),
        ),
    ]
