# Generated by Django 5.1 on 2024-11-18 19:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DirectionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Название категории направления"
                    ),
                ),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Тэг направления",
                "verbose_name_plural": "Тэги направления",
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Название направления"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="direction/image/%Y/%m/%d/",
                        verbose_name="Главное изображение направления",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", verbose_name="Описание направления"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="directions",
                        to="directions.directiontag",
                        verbose_name="Категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
    ]
