# Generated by Django 5.1 on 2024-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directiontag",
            name="description",
            field=models.CharField(max_length=200, verbose_name="Описание"),
        ),
    ]
