# Generated by Django 5.1 on 2024-11-18 19:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="halls/photos/", verbose_name="Изображение"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Описание фотографии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография зала",
                "verbose_name_plural": "Фотографии зала",
            },
        ),
        migrations.CreateModel(
            name="HallCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Адрес")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", verbose_name="Описание"
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(to="halls.photo", verbose_name="Фотографии"),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=20, verbose_name="Название зала"),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", verbose_name="Описание"
                    ),
                ),
                ("square", models.PositiveIntegerField(verbose_name="Площадь зала")),
                (
                    "hall_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halls",
                        to="halls.hallcenter",
                        verbose_name="Локация",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(to="halls.photo", verbose_name="Фотографии"),
                ),
            ],
            options={
                "verbose_name": "Зал",
                "verbose_name_plural": "Залы",
            },
        ),
    ]
