# Generated by Django 5.1 on 2025-01-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Описание фотографии'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='halls/photos/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
